FROM golang:latest

RUN go version
WORKDIR /

COPY go.mod go.sum ./
RUN go mod download

RUN apt-get update && apt-get -y install postgresql-client

COPY . .

RUN go build -o tonwork-back ./cmd/main.go

CMD ["./tonwork-back"]