installdb:
	docker pull postgres
build:
	docker run --name=ton-work -e POSTGRES_PASSWORD='123321' -p 5436:5432 -d --rm postgres
migrate:
	migrate -path ./schema -database "postgres://postgres:123321@localhost:5436/postgres?sslmode=disable" up
run:
	go run cmd/main.go
